// Generated by https://quicktype.io

export interface ProductsResponse {
	data: Datum[]
	count: number
	totalPages: number
}

export interface Datum {
	id: string
	name: string
	code: string
	categoryName: string
	description: string
	price: number
	stock: number
	isAvailable: boolean
	imageUrl: string
}
